# CMake generated Testfile for 
# Source directory: /hw2/amazon_tests
# Build directory: /hw2/amazon_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(DatabaseReadback.EmptyDatabase "/hw2/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.EmptyDatabase")
set_tests_properties(DatabaseReadback.EmptyDatabase PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(DatabaseReadback.Book "/hw2/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.Book")
set_tests_properties(DatabaseReadback.Book PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(DatabaseReadback.Clothing "/hw2/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.Clothing")
set_tests_properties(DatabaseReadback.Clothing PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(DatabaseReadback.Movie "/hw2/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.Movie")
set_tests_properties(DatabaseReadback.Movie PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(DatabaseReadback.User "/hw2/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.User")
set_tests_properties(DatabaseReadback.User PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(DatabaseReadback.Mixed "/hw2/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.Mixed")
set_tests_properties(DatabaseReadback.Mixed PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.Quit "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.Quit")
set_tests_properties(ConsoleInterface.Quit PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.HitBook "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.HitBook")
set_tests_properties(ConsoleInterface.HitBook PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.HitClothing "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.HitClothing")
set_tests_properties(ConsoleInterface.HitClothing PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.HitMovie "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.HitMovie")
set_tests_properties(ConsoleInterface.HitMovie PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.CaseInsensitive "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.CaseInsensitive")
set_tests_properties(ConsoleInterface.CaseInsensitive PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.HugeQuantity "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.HugeQuantity")
set_tests_properties(ConsoleInterface.HugeQuantity PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.AddOneToCart "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddOneToCart")
set_tests_properties(ConsoleInterface.AddOneToCart PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(Database.BuyCart "/hw2/amazon_tests/amazon_tests" "--gtest_filter=Database.BuyCart")
set_tests_properties(Database.BuyCart PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(DatabaseReadback.ThreeBooks "/hw2/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.ThreeBooks")
set_tests_properties(DatabaseReadback.ThreeBooks PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(DatabaseReadback.ThreeClothes "/hw2/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.ThreeClothes")
set_tests_properties(DatabaseReadback.ThreeClothes PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(DatabaseReadback.ThreeMovies "/hw2/amazon_tests/amazon_tests" "--gtest_filter=DatabaseReadback.ThreeMovies")
set_tests_properties(DatabaseReadback.ThreeMovies PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.AddTwoItems "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddTwoItems")
set_tests_properties(ConsoleInterface.AddTwoItems PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.AddTwoIdenticalItems "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddTwoIdenticalItems")
set_tests_properties(ConsoleInterface.AddTwoIdenticalItems PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(Database.BuyCartTwoItems "/hw2/amazon_tests/amazon_tests" "--gtest_filter=Database.BuyCartTwoItems")
set_tests_properties(Database.BuyCartTwoItems PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.OrMultipleHit "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.OrMultipleHit")
set_tests_properties(ConsoleInterface.OrMultipleHit PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.AndMultipleHit "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AndMultipleHit")
set_tests_properties(ConsoleInterface.AndMultipleHit PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.AddToTwoUsersCarts "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddToTwoUsersCarts")
set_tests_properties(ConsoleInterface.AddToTwoUsersCarts PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.AddSameProductTwoUsersCarts "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddSameProductTwoUsersCarts")
set_tests_properties(ConsoleInterface.AddSameProductTwoUsersCarts PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.AddTwoProductsTwoUsers "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddTwoProductsTwoUsers")
set_tests_properties(ConsoleInterface.AddTwoProductsTwoUsers PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(Database.BuyTwoProductsTwoUsers "/hw2/amazon_tests/amazon_tests" "--gtest_filter=Database.BuyTwoProductsTwoUsers")
set_tests_properties(Database.BuyTwoProductsTwoUsers PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.BuyCartInsufficientFunds "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.BuyCartInsufficientFunds")
set_tests_properties(ConsoleInterface.BuyCartInsufficientFunds PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(Database.BuyCartInsufficientFunds "/hw2/amazon_tests/amazon_tests" "--gtest_filter=Database.BuyCartInsufficientFunds")
set_tests_properties(Database.BuyCartInsufficientFunds PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleInterface.AddItemToMultipleUsers "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleInterface.AddItemToMultipleUsers")
set_tests_properties(ConsoleInterface.AddItemToMultipleUsers PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(Database.BuySingleStockItemMultipleUsers "/hw2/amazon_tests/amazon_tests" "--gtest_filter=Database.BuySingleStockItemMultipleUsers")
set_tests_properties(Database.BuySingleStockItemMultipleUsers PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleErrors.ViewCartUnknownUser "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleErrors.ViewCartUnknownUser")
set_tests_properties(ConsoleErrors.ViewCartUnknownUser PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleErrors.BuyCartUnknownUser "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleErrors.BuyCartUnknownUser")
set_tests_properties(ConsoleErrors.BuyCartUnknownUser PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(ConsoleErrors.AddInvalidHitToCart "/hw2/amazon_tests/amazon_tests" "--gtest_filter=ConsoleErrors.AddInvalidHitToCart")
set_tests_properties(ConsoleErrors.AddInvalidHitToCart PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(AmazonStress.Buy10000Products "/hw2/amazon_tests/amazon_tests" "--gtest_filter=AmazonStress.Buy10000Products")
set_tests_properties(AmazonStress.Buy10000Products PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
add_test(AmazonStress.AndSearch10000Products "/hw2/amazon_tests/amazon_tests" "--gtest_filter=AmazonStress.AndSearch10000Products")
set_tests_properties(AmazonStress.AndSearch10000Products PROPERTIES  _BACKTRACE_TRIPLES "/hw2/test_cmake_lib/CustomTests.cmake;45;add_test;/hw2/test_cmake_lib/TestTargets.cmake;199;add_executable_gtests;/hw2/amazon_tests/CMakeLists.txt;2;add_makefile_problem;/hw2/amazon_tests/CMakeLists.txt;0;")
